from __future__ import annotations

SCENARIO_STAGE = "scenario"
GENERATION_STAGE = "generation"
VALIDATION_STAGE = "validation"
RENDER_STAGE = "render"

SCENARIO_PARSE_FAILED = "SCENARIO_PARSE_FAILED"
TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"
SLOT_SCHEMA_NOT_FOUND = "SLOT_SCHEMA_NOT_FOUND"
PROMPT_NOT_FOUND = "PROMPT_NOT_FOUND"
PROMPT_RESOURCE_PARSE_ERROR = "prompt_resource_parse_error"
PROMPT_RESOURCE_ACCESS_ERROR = "prompt_resource_access_error"
INVALID_LLM_OUTPUT = "INVALID_LLM_OUTPUT"
MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
LLM_EXECUTION_FAILED = "LLM_EXECUTION_FAILED"
RENDER_FAILED = "RENDER_FAILED"
